#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig

about:
    path: /about
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/about.html.twig

contact:
    path: /contact
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/contact.html.twig

developers:
    path: /developers
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/developers.html.twig

docs:
    path: /docs
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/docs.html.twig

pricing:
    path: /pricing
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/pricing.html.twig

features:
    path: /features
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/features.html.twig

faqs:
    path: /faqs
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/faqs.html.twig

mission:
    path: /mission
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/mission.html.twig

privacy:
    path: /privacy
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/privacy.html.twig

terms:
    path: /terms
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/terms.html.twig

tutorial:
    path: /tutorial
    #controller: App\Controller\DefaultController::homepage
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/tutorial.html.twig